NDefines.NAI.AGGRESSIVENESS = 10
NDefines.NAI.GGRESSIVENESS_BONUS_EASY_WAR = 90
NDefines.NAI.DIPLOMATIC_INTEREST_DISTANCE = 100
NDefines.NAI.CONQUEST_INTEREST_DISTANCE = 50
NDefines.NAI.PEACE_DESPERATION_FACTOR = 100
NDefines.NAI.PEACE_TERMS_PROVINCE_IMPERIAL_LIBERATION_MULT = 0.1
NDefines.NAI.PEACE_TERMS_PROVINCE_NO_CB_MULT = 0.25
NDefines.NAI.PEACE_TERMS_PROVINCE_CORE_MULT = 5.0
NDefines.NAI.PEACE_TERMS_PROVINCE_WARGOAL_MULT = 3.0
NDefines.NAI.PEACE_TERMS_PROVINCE_NOT_CULTURE_MULT = 0.25
NDefines.NAI.PEACE_TERMS_PROVINCE_VASSAL_MULT = 1.25
NDefines.NAI.PEACE_TERMS_PROVINCE_NOT_ADJACENT_MULT = 0.25
NDefines.NAI.PEACE_TERMS_PROVINCE_OVEREXTENSION_MIN_MULT = 1.0
NDefines.NAI.PEACE_TERMS_PROVINCE_OVEREXTENSION_MAX_MULT = 1.0
NDefines.NAI.PEACE_TERMS_PROVINCE_ISOLATED_CAPITAL_MULT = 0.5

NDefines.NReligion.MAX_CHRISTIAN_RELIGIOUS_CENTERS = 3

NDefines.NCountry.PRIMARY_NATION_BLOCK_CONVERT_CULTURE = 1
NDefines.NCountry.CAN_CONVERT_TERRITORY_CULTURE = 0
NDefines.NCountry.CAN_CONVERT_TERRITORY_RELIGION = 0


